### ISSUE TITLE
The "ci" workflow is broken

### ISSUE THREAD

**Issue by Ostrzyciel** [Kaszanas/SC2InfoExtractorGo#55] opened 2023-12-19 14:19 UTC
Executing the job in PRs yields an error: https://github.com/Kaszanas/SC2InfoExtractorGo/actions/runs/7263055521/job/19787533745?pr=53

I'm not a huge fan of makefile... but it seems that the jobs are misconfigured.

**Comment by Kaszanas** [comment] 2024-05-11 01:55
@Ostrzyciel This should be fixed by now.

Currently there is no automatic tests running. So the CI is only verifying if the Dockerfiles are built as intended.

Additional CI step will be added after the tests are prepared and ready to be included.
So far the main test is being able to reproduce the dataset.

Most likely after our submission.
Closing this for now.

**Closed by Kaszanas** 2024-05-11 01:55 UTC
Labels: bug
